version: "3.9"

services:
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    command: "yarn debug"
    working_dir: /app
    volumes:
      - .:/app:cached
    ports:
      - "5000:5000"